icons = "awesome"

[theme]
name = "plain"

[theme.overrides]
idle_bg = "#222222"
idle_fg = "#80809e"
separator_bg = "#222222"
good_bg = "#222222"
warning_bg = "#222222"
critical_bg = "#222222"
info_bg = "#222222"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

#[[block]]
#block = "toggle"
#text = "4k"
#command_state = "xrandr | rg HDMI-1\\ connected | rg -v HDMI-1"
#command_on = "~/.screenlayout/homeoffice.sh"
#command_off = "~/.screenlayout/just_laptop.sh"
#interval = 5

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"

[[block]]
block = "pacman"
interval = 600
